name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS region
        run: echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377199948.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t demo-application .

      - name: Tag Docker image
        run: docker tag demo-application:latest 891377199948.dkr.ecr.us-east-1.amazonaws.com/demo-repo:latest

      - name: Push Docker image to ECR
        run: docker push 891377199948.dkr.ecr.us-east-1.amazonaws.com/demo-repo:latest

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster demo-cluster --service demo-service --force-new-deployment
