name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS region
        run: echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Create ECR Repository
        run: |
          aws ecr create-repository --repository-name demo-repo --region us-east-1 || true

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377199948.dkr.ecr.us-east-1.amazonaws.com

      - name: Check if ECS cluster exists
        id: check_cluster
        run: |
          aws ecs describe-clusters --clusters demo-cluster --region us-east-1 || echo "::set-output name=cluster_exists::false"

      - name: Create ECS cluster if it doesn't exist
        if: steps.check_cluster.outputs.cluster_exists == 'false'
        run: aws ecs create-cluster --cluster-name demo-cluster --region us-east-1

      - name: Register task definition
        id: register_task_definition
        run: |
          TASK_DEF=$(aws ecs register-task-definition \
            --family demo-task \
            --container-definitions '[{"name":"demo-container","image":"891377199948.dkr.ecr.us-east-1.amazonaws.com/demo-repo:latest", "memory":512, "memoryReservation":256}]' \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text \
            --region us-east-1)
          echo "::set-output name=task_def::${TASK_DEF##*/}"
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1

      - name: Create ECS service with Fargate launch type
        if: steps.check_cluster.outputs.cluster_exists == 'true'
        run: |
          aws ecs create-service \
            --cluster demo-cluster \
            --service-name demo-service \
            --task-definition ${{ steps.register_task_definition.outputs.task_def }} \
            --desired-count 1 \
            --launch-type "FARGATE" \
            --region us-east-1
